### PR TITLE
Add tool versions to gitignore

### PR DESCRIPTION
**Pull request by berlintam**

### CODE REVIEW

**Comment by jnsya** [comment]
We're adding a tool-versions line to the gitignore, but we don't seem to have the file itself in this repo? Or does adding the line to the gitignore do some magic?

**Comment by berlintam** [comment]
We added it to the gitignore to allow us to add one locally, but in reality, the package should work w/ multiple versions of Elixir & Erlang.

**Comment by Joerg-Seitz** [comment]
Test this please

**Comment by andreasknoepfle** [comment]
> We added it to the gitignore to allow us to add one locally, but in reality, the package should work w/ multiple versions of Elixir & Erlang.

It is true that in reality the library should work with multiple versions of elixir. But I would say that most of the time this is done by CI and there is still one development version, that is the suggested version for developing and that makes it easy to install for new devs. 
Testing the library against different version can be done in Travis by building a version matrix with different base images.

Since this PR is super old and I believe the value is questionable I would suggest closing this.

**Comment by sliminas** [comment]
:+1:

**Pull request closed without merging**
